import { useCallback, useRef, useState } from "react";

import { type NextPage } from "next";

import Head from "next/head";
import Image from "next/image";

import classnames from "classnames";

import { Plus, Hash, Trash } from "phosphor-react";

import { trpc } from "../../utils/trpc";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { formatDistanceToNow } from "date-fns";

const Server: NextPage = () => {
  const [activeChannel, setActiveChannel] = useState<string>("");

  const channelRef = useRef<HTMLInputElement>(null);
  const messageRef = useRef<HTMLInputElement>(null);

  const chatRef = useRef<HTMLDivElement>(null);

  const router = useRouter();

  const { data: sessionData } = useSession();

  const serverId = router.query.serverId as string;

  const server = trpc.server.show.useQuery({ id: serverId });

  const channel = trpc.server.getChannel.useQuery({ id: activeChannel });

  const createChannel = trpc.server.createChannel.useMutation({
    onSuccess: () => {
      server.refetch();
    },
  });

  const deleteChannel = trpc.server.deleteChannel.useMutation({
    onSuccess: () => {
      server.refetch();
    },
  });

  const createMessage = trpc.server.createMessage.useMutation({
    onSuccess: () => {
      channel.refetch();
    },
  });

  const handleSubmit = useCallback(
    async (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault();

      await createChannel.mutateAsync({
        name: channelRef.current?.value ?? "New channel",
        serverId,
      });

      if (channelRef.current) channelRef.current.value = "";
    },
    [createChannel, serverId]
  );

  const handleChangeChannel = useCallback((channelId: string) => {
    setActiveChannel(channelId);
  }, []);

  const handleDeleteChannel = useCallback(
    async (channelId: string) => {
      await deleteChannel.mutateAsync({ id: channelId });

      if (activeChannel === channelId) setActiveChannel("");
    },
    [activeChannel, deleteChannel]
  );

  const handleSendMessage = useCallback(
    async (e: React.FormEvent<HTMLFormElement>) => {
      e.preventDefault();

      await createMessage.mutateAsync({
        content: messageRef.current?.value ?? "New message",
        channelId: activeChannel,
      });

      if (messageRef.current) messageRef.current.value = "";
    },
    [createMessage, activeChannel]
  );

  if (!sessionData?.user) return <div>Not logged in</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex max-h-screen min-h-screen overflow-y-auto overflow-x-hidden bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex min-h-full w-full items-stretch justify-start">
          <div className="flex h-full w-96 flex-col justify-between bg-zinc-700">
            <div className="flex flex-col gap-4">
              <div className="flex h-12 w-full items-center border-b-[1px] border-zinc-800 px-6 font-semibold text-white">
                {server?.data?.name}
              </div>

              <div className="flex flex-col gap-4 px-4 py-4">
                <div className="flex items-center">
                  <form className="flex w-full gap-4" onSubmit={handleSubmit}>
                    <input
                      className="h-8 flex-1 rounded-full bg-zinc-600 px-4 text-white "
                      type="text"
                      placeholder="Channel name"
                      ref={channelRef}
                    />

                    <button
                      type="submit"
                      className="flex h-8 w-8 items-center justify-center rounded-full bg-zinc-600 text-white hover:bg-zinc-500"
                    >
                      <Plus />
                    </button>
                  </form>
                </div>

                <div className="flex flex-col gap-2">
                  {server?.data?.channels.map((channel) => (
                    <div
                      key={channel.id}
                      className={classnames(
                        "group flex items-center rounded-xl px-2",
                        {
                          "bg-zinc-600 text-white":
                            activeChannel === channel.id,
                          "text-white hover:bg-zinc-500":
                            activeChannel !== channel.id,
                        }
                      )}
                    >
                      <button
                        onClick={() => handleChangeChannel(channel.id)}
                        className="flex h-full w-full items-center gap-4 py-2"
                      >
                        <span className="text-xl text-zinc-400">
                          <Hash />
                        </span>

                        {channel.name}
                      </button>

                      <button
                        className="flex h-full items-center justify-center gap-4 py-2 text-zinc-400 hover:text-white"
                        onClick={() => {
                          handleDeleteChannel(channel.id);
                        }}
                      >
                        <span className="hidden text-xl group-hover:block">
                          <Trash />
                        </span>
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <div className="flex w-full items-center justify-start gap-2 bg-zinc-800 px-2 py-2">
              <Image
                src={sessionData.user.image as string}
                alt=""
                className="rounded-full"
                height={32}
                width={32}
              />

              <p className="font-semibold text-white">
                {sessionData.user.name}
              </p>
            </div>
          </div>

          <div className="flex h-full w-full flex-col bg-zinc-600">
            <div className="flex h-12 items-center border-b-[1px] border-zinc-700 px-4">
              <span className="text-2xl text-zinc-400">
                <Hash />
              </span>

              <p className="ml-2 font-semibold text-white">
                {channel?.data?.name}
              </p>
            </div>

            <div
              ref={chatRef}
              className="flex flex-1 flex-col-reverse overflow-x-auto px-4"
            >
              <ul className="flex flex-col gap-4 py-4">
                {channel?.data?.messages.map((message) => (
                  <li key={message.id} className="flex items-center gap-4">
                    <Image
                      className="rounded-full"
                      height={40}
                      width={40}
                      src={message.author.image as string}
                      alt=""
                    />

                    <div className="flex flex-col">
                      <div className="flex gap-2">
                        <p className="font-semibold text-yellow-400">
                          {message.author.name}
                        </p>

                        <p className="text-zinc-400">
                          {formatDistanceToNow(new Date(message.createdAt))}
                        </p>
                      </div>

                      <p className="text-zinc-100">{message.content}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>

            <div className="px-4 pb-6 pt-2">
              <form
                className="flex items-center gap-4"
                onSubmit={handleSendMessage}
              >
                <input
                  className="h-12 flex-1 rounded-xl bg-zinc-700 px-4 text-white placeholder:text-zinc-400"
                  type="text"
                  placeholder={`Message #${channel?.data?.name}`}
                  ref={messageRef}
                />
              </form>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Server;
